apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebookmgmt-book
  labels:
    app: ebookmgmt-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebookmgmt-book
  template:
    metadata:
      labels:
        app: ebookmgmt-book
    spec:
      containers:
        - name: ebookmgmt-book
          image: username/ebookmgmt-book:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5